apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - external-secrets.yaml
  - deployment-web.yaml
  - deployment-worker.yaml
  - deployment-scheduler.yaml
  - job-migration.yaml
  - hpa.yaml
  - serviceaccount.yaml
  - secret-provider-class.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: status-page-app
    newName: 992382545251.dkr.ecr.us-east-1.amazonaws.com/yosef-aviv-status-page-prod
    newTag: latest