# values.yaml

# Namespace
namespace: "default"

# Image Configuration
image:
  repository: 992382545251.dkr.ecr.us-east-1.amazonaws.com/yosef-aviv-status-page-prod
  tag: "129885a377f0514119e127df7815bdf6616540c7"
  pullPolicy: Always

# Scaling
web:
  replicaCount: 2
  minReplicas: 2
  maxReplicas: 10
worker:
  replicaCount: 1
  minReplicas: 1
  maxReplicas: 5

# Networking
ingress:
  host: yosef-aviv-statuspage.xyz
  certificateArn: "arn:aws:acm:us-east-1:992382545251:certificate/c5972ef3-8014-4d82-a608-9224e4faad02"
  wafAclArn: "arn:aws:wafv2:us-east-1:992382545251:regional/webacl/yosef-aviv-status-page-prod-waf/fe6441f0-4942-4caf-bd91-e795aac5ce88"

# AWS / Infrastructure
aws:
  region: us-east-1
  roleArn: "arn:aws:iam::992382545251:role/yosef-aviv-status-page-prod-irsa-role"
  paramStorePath: "/yosef-aviv-status-page-prod"
  secretsManagerNamePrefix: "yosef-aviv-status-page-prod"

# Resources
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"