apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-parameter-store
  namespace: {{ .Values.namespace }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: status-page-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: status-page-infra-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-parameter-store
    kind: SecretStore
  target:
    name: status-page-infra-secrets
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: "{{ .Values.aws.paramStorePath }}/db/host"
    - secretKey: REDIS_HOST
      remoteRef:
        key: "{{ .Values.aws.paramStorePath }}/redis/host"
    - secretKey: STATIC_URL
      remoteRef:
        key: "{{ .Values.aws.paramStorePath }}/s3/static_url"