apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: status-page-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: status-page-infra-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-parameter-store
    kind: SecretStore
  target:
    name: status-page-infra-secrets
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: /yosef-aviv-status-page-prod/db/host
    - secretKey: REDIS_HOST
      remoteRef:
        key: /yosef-aviv-status-page-prod/redis/host
    - secretKey: STATIC_URL
      remoteRef:
        key: /yosef-aviv-status-page-prod/s3/static_url