apiVersion: v1
kind: ServiceAccount
metadata:
  name: status-page-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::992382545251:role/yosef-aviv-status-page-prod-irsa-role # Replace with your actual AWS account ID and IAM role name